export const ComponentIDs = {
  addComment: 'addComment',
  comment: 'comment',
  deleteComment: 'deleteComment',
  deletePost: 'deletePost',
  fileField: 'fileField',
  footer: 'footer',
  loadingSpinner: 'loadingSpinner',
  modCard: 'modCard',
  navBar: 'navBar',
  currentUserDropDown: 'currentUserDropDown',
  navBarSignIn: 'navBarSignIn',
  navBarSignOut: 'navBarSignOut',
  navBarSignUp: 'navBarSignUp',
  navBarCivicEngagementItem: 'navBarCivicEngagementItem',
  navBarVisualizeToolsetItem: 'navBarVisualizeToolsetItem',
  post: 'post',
  profile: 'profile',
  survey: 'survey',
};

export const PageIDs = {
  addModCard: 'addModCard',
  addPost: 'addPost',
  addProfile: 'addProfile',
  addSurvey: 'addSurvey',
  communityPage: 'communityPage',
  dalle3: 'dalle3',
  editProfile: 'editProfile',
  external: 'external',
  forum: 'forum',
  landing: 'landing',
  mapping: 'mapping',
  model: 'model',
  notAuthorized: 'notAuthorized',
  notFound: 'notFound',
  signIn: 'signIn',
  signOut: 'signOut',
  signUp: 'signUp',
  surveyPage: 'surveyPage',
};
